In [ ]:
!pip install pandas
!pip install openpyxl
import pandas as pd
import openpyxl

In [6]:
df = pd.read_excel("CD2022_Populacao_2010_Compatibilizada_20231222.xlsx", header=2)

In [26]:
df

,Unnamed: 0,UF,COD. UF,COD. MUNIC,NOME DO MUNICÍPIO,População Município 2010\n(Sinopse),População 2010 (Alterações de Limites até 2022)1,População Censo 2022
0,NaN,RO,11.0,15.0,Alta Floresta D'Oeste,24392.0,24392.0,21494.0
1,NaN,RO,11.0,23.0,Ariquemes,90353.0,90353.0,96833.0
2,NaN,RO,11.0,31.0,Cabixi,6313.0,6313.0,5351.0
3,NaN,RO,11.0,49.0,Cacoal,78574.0,78574.0,86887.0
4,NaN,RO,11.0,56.0,Cerejeiras,17029.0,17029.0,15890.0
...,...,...,...,...,...,...,...,...
5569,NaN,DF,53.0,108.0,Brasília,2570160.0,2572159.0,2817381.0
5570,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5571,NaN,Nota: Para o cálculo das taxas de crescimento ...,NaN,NaN,NaN,NaN,NaN,NaN
5572,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5573,NaN,Fonte: IBGE. Diretoria de Pesquisas - DPE - C...,NaN,NaN,NaN,NaN,NaN,NaN

In [33]:
tabela_tratada = df.iloc[:5570, 1:]
tabela_tratada

,UF,COD. UF,COD. MUNIC,NOME DO MUNICÍPIO,População Município 2010\n(Sinopse),População 2010 (Alterações de Limites até 2022)1,População Censo 2022
0,RO,11.0,15.0,Alta Floresta D'Oeste,24392.0,24392.0,21494.0
1,RO,11.0,23.0,Ariquemes,90353.0,90353.0,96833.0
2,RO,11.0,31.0,Cabixi,6313.0,6313.0,5351.0
3,RO,11.0,49.0,Cacoal,78574.0,78574.0,86887.0
4,RO,11.0,56.0,Cerejeiras,17029.0,17029.0,15890.0
...,...,...,...,...,...,...,...
5565,GO,52.0,22005.0,Vianópolis,12548.0,12548.0,14956.0
5566,GO,52.0,22054.0,Vicentinópolis,7371.0,7373.0,8768.0
5567,GO,52.0,22203.0,Vila Boa,4735.0,4735.0,4215.0
5568,GO,52.0,22302.0,Vila Propício,5145.0,5145.0,5815.0
5569,DF,53.0,108.0,Brasília,2570160.0,2572159.0,2817381.0

In [29]:
tabela_estado = tabela_tratada.groupby("UF")[["População Município 2010\n(Sinopse)", "População Censo 2022"]].sum().reset_index()

In [31]:
tabela_estado["Crescimento"] = tabela_estado["População Censo 2022"] - tabela_estado["População Município 2010\n(Sinopse)"]

In [32]:
tabela_estado.to_csv(r"H:\atividade 4\tabela_estado.csv", sep =";")

In [35]:
tabela_cidade = tabela_tratada.iloc[:, 3:]
tabela_cidade

,NOME DO MUNICÍPIO,População Município 2010\n(Sinopse),População 2010 (Alterações de Limites até 2022)1,População Censo 2022
0,Alta Floresta D'Oeste,24392.0,24392.0,21494.0
1,Ariquemes,90353.0,90353.0,96833.0
2,Cabixi,6313.0,6313.0,5351.0
3,Cacoal,78574.0,78574.0,86887.0
4,Cerejeiras,17029.0,17029.0,15890.0
...,...,...,...,...
5565,Vianópolis,12548.0,12548.0,14956.0
5566,Vicentinópolis,7371.0,7373.0,8768.0
5567,Vila Boa,4735.0,4735.0,4215.0
5568,Vila Propício,5145.0,5145.0,5815.0
5569,Brasília,2570160.0,2572159.0,2817381.0

In [36]:
tabela_cidade.to_csv(r"H:\atividade 4\tabela_cidade.csv", sep =";")